title: Lishuo Dong's Homepage
page-top-title: Lishuo Dong
top-section-bg-text: Computational Mathematics
home-subtitle: Lishuo Dong&ensp;|&ensp;董立硕
copyright-text: '&copy; Lishuo Dong 2021-2025. All Rights Reserved.'
